version: "3.7"
services:
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
